-- =============================================================================
-- Full 2026 budget apply from public._budget_truth_csv with agreed mapping rules.
--
-- Input:
--   public._budget_truth_csv generated by scripts/reconcile-budget-csv.mjs
--   Columns: initiative, budget_department, q1..q4, is_in_pnl_it.
--
-- Applies:
--   - direct rows for initiatives with a unique name in public.initiatives;
--   - agreed MAP / CREATE / REDISTRIBUTE / SKIP rules from the previous flow;
--   - full rewrite of initiative_budget_department_2026;
--   - 2026 quarterly_data cost = sum of final budget split;
--   - 2025-Q* keys removed from initiatives.quarterly_data.
-- Uses public._budget_2026_* staging tables instead of TEMP tables because
-- Supabase SQL Editor may commit between statements and drop ON COMMIT tables.
-- =============================================================================

DO $guard$
BEGIN
  IF to_regclass('public._budget_truth_csv') IS NULL THEN
    RAISE EXCEPTION 'Нет public._budget_truth_csv. Сначала выполните сгенерированный *-truth-insert.sql';
  END IF;

  IF to_regclass('public.initiative_budget_department_2026') IS NULL THEN
    RAISE EXCEPTION 'Нет public.initiative_budget_department_2026. Сначала примените миграцию таблицы разбивки';
  END IF;
END
$guard$;

ALTER TABLE public.initiative_budget_department_2026
  ADD COLUMN IF NOT EXISTS is_in_pnl_it boolean NOT NULL DEFAULT true;

ALTER TABLE public.initiative_budget_department_2026
  ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now());

ALTER TABLE public.initiative_budget_department_2026
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now());

BEGIN;

CREATE TABLE IF NOT EXISTS public.budget_import_2026_rules (
  source_initiative text NOT NULL,
  budget_department text NOT NULL,
  action text NOT NULL CHECK (action IN ('MAP','CREATE','REDISTRIBUTE','SKIP')),
  target_initiative_id uuid,
  create_unit text,
  create_team text,
  create_initiative text,
  note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (source_initiative, budget_department)
);

DROP TABLE IF EXISTS public.budget_import_2026_exceptions;
CREATE TABLE public.budget_import_2026_exceptions (
  reason text NOT NULL,
  initiative text,
  details jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

DROP TABLE IF EXISTS
  public._budget_2026_final_sum,
  public._budget_2026_final_rows,
  public._budget_2026_redist_alloc,
  public._budget_2026_recipients,
  public._budget_2026_redist_source,
  public._budget_2026_unresolved,
  public._budget_2026_mapped,
  public._budget_2026_create_defs,
  public._budget_2026_ini_once,
  public._budget_2026_src;

CREATE TABLE public._budget_2026_src AS
SELECT
  trim(initiative) AS source_initiative,
  trim(budget_department) AS budget_department,
  sum(q1)::numeric AS q1,
  sum(q2)::numeric AS q2,
  sum(q3)::numeric AS q3,
  sum(q4)::numeric AS q4,
  bool_or(coalesce(is_in_pnl_it, true)) AS is_in_pnl_it
FROM public._budget_truth_csv
WHERE trim(coalesce(initiative, '')) <> ''
GROUP BY 1, 2;

CREATE TABLE public._budget_2026_ini_once AS
SELECT
  trim(initiative) AS source_initiative,
  (array_agg(id ORDER BY id))[1] AS initiative_id
FROM public.initiatives
WHERE coalesce(is_timeline_stub, false) = false
GROUP BY trim(initiative)
HAVING count(*) = 1;

-- Hand-agreed MAP rules.
INSERT INTO public.budget_import_2026_rules (source_initiative, budget_department, action, target_initiative_id, note)
SELECT 'GDPR', dep, 'MAP', (array_agg(i.id ORDER BY i.id))[1], 'GDPR -> TMNT'
FROM (VALUES
  ('IT.App & Web.Core'),
  ('IT.App & Web.Management'),
  ('IT.Management')
) d(dep)
JOIN public.initiatives i
  ON i.initiative = 'GDPR' AND i.unit = 'App&Web' AND i.team = 'TMNT'
GROUP BY dep
ON CONFLICT (source_initiative, budget_department) DO UPDATE
SET action = excluded.action, target_initiative_id = excluded.target_initiative_id, note = excluded.note;

INSERT INTO public.budget_import_2026_rules (source_initiative, budget_department, action, target_initiative_id, note)
SELECT 'GDPR Postal', dep, 'MAP', (array_agg(i.id ORDER BY i.id))[1], 'GDPR Postal -> App&Web/Postal'
FROM (VALUES
  ('IT.App & Web.Management'),
  ('IT.App & Web.Postal'),
  ('IT.Management')
) d(dep)
JOIN public.initiatives i
  ON i.initiative = 'GDPR' AND i.unit = 'App&Web' AND i.team = 'Postal'
GROUP BY dep
ON CONFLICT (source_initiative, budget_department) DO UPDATE
SET action = excluded.action, target_initiative_id = excluded.target_initiative_id, note = excluded.note;

INSERT INTO public.budget_import_2026_rules (source_initiative, budget_department, action, target_initiative_id, note)
SELECT 'Динамический промис', dep, 'MAP', (array_agg(i.id ORDER BY i.id))[1], 'Client Platform -> Peaches'
FROM (VALUES
  ('IT.Client Platform.Management'),
  ('IT.Client Platform.Personalisation')
) d(dep)
JOIN public.initiatives i
  ON i.initiative = 'Динамический промис' AND i.unit = 'Client Platform' AND i.team = 'Peaches'
GROUP BY dep
ON CONFLICT (source_initiative, budget_department) DO UPDATE
SET action = excluded.action, target_initiative_id = excluded.target_initiative_id, note = excluded.note;

INSERT INTO public.budget_import_2026_rules (source_initiative, budget_department, action, target_initiative_id, note)
SELECT 'Динамический промис', 'IT.Data Office.AI Lab', 'MAP', (array_agg(i.id ORDER BY i.id))[1], 'Data Office ветка'
FROM public.initiatives i
WHERE i.initiative = 'Динамический промис' AND i.unit = 'Data Office' AND i.team = 'Personalisation'
GROUP BY i.initiative
ON CONFLICT (source_initiative, budget_department) DO UPDATE
SET action = excluded.action, target_initiative_id = excluded.target_initiative_id, note = excluded.note;

-- Rename/FOT alias rules.
WITH alias_map(source_initiative, target_initiative) AS (
  VALUES
    ('Aggregators ФОТ Q1 25 - Q4 26', 'Aggregators Стоимость команды Q1 25 - Q4 26'),
    ('Architecture ФОТ', 'Architecture Стоимость команды'),
    ('B2C IT Team ФОТ', 'B2C IT Team Стоимость команды'),
    ('Codo ФОТ Q1 25 - Q4 26', 'Codo Стоимость команды Q1 25 - Q4 26'),
    ('Partner Support ФОТ Q2-Q4', 'Partner Support Стоимость команды'),
    ('POS B2B Остаток ФОТа Q1 25, Q2-Q3-Q4 26', 'POS B2B Остаток Стоимость команды Q1 25, Q2-Q3-Q4 26'),
    ('ФОт 2026 Q2-Q4', 'Стоимость команды 2026 Q2-Q4'),
    ('ФОТ B2B дизайн 2025-2026', 'Стоимость команды B2B дизайн 2025-2026'),
    ('ФОТ B2С Аналитики 2025-2026', 'Стоимость команды B2С Аналитики 2025-2026'),
    ('ФОТ Delivery (без CM) Q2-Q4 26', 'Стоимость команды Delivery (без CM) Q2-Q4 26'),
    ('ФОТ Flacky Ramen 2025-2026', 'Стоимость команды Flacky Ramen 2025-2026'),
    ('ФОТ Infrastructure 2025-2026', 'Стоимость команды Infrastructure 2025-2026'),
    ('Фот Lolypop Q2-Q4 2026', 'Стоимость команды Lolypop Q2-Q4 2026'),
    ('ФОТ mOrder Q2-Q4 2026', 'Стоимость команды mOrder Q2-Q4 2026'),
    ('ФОТ Perfomance 2025-2026', 'Стоимость команды Perfomance 2025-2026'),
    ('ФОТ Postal Q1 2025 +Q2-Q4 2026', 'Стоимость команды Postal Q1 2025 +Q2-Q4 2026'),
    ('ФОТ X-men(u) Q2-Q4 26', 'Стоимость команды X-men(u) Q2-Q4 2026'),
    ('фОТ команды Kitchen Experience Q1 - Q4 2025 + Q2 - Q4 2026', 'Стоимость команды команды Kitchen Experience Q1 - Q4 2025 + Q2 - Q4 2026'),
    ('ФОТ кор команды', 'Стоимость команды кор команды'),
    ('Заглушка ФОТ Cusomet Support Q2-Q4 2026', 'Заглушка Стоимость команды Cusomet Support Q2-Q4 2026'),
    ('Заглушка ФОТ SOM Q2-Q4 2026', 'Стоимость команды SOM Q2-Q4 2026'),
    ('Остаток ФОТА Q3-Q4 Purrr', 'Стоимость команды Q3-Q4 Purrr')
)
INSERT INTO public.budget_import_2026_rules (
  source_initiative, budget_department, action, target_initiative_id, note
)
SELECT
  s.source_initiative,
  s.budget_department,
  'MAP',
  u.initiative_id,
  'auto MAP by alias_map'
FROM public._budget_2026_src s
JOIN alias_map a ON a.source_initiative = s.source_initiative
JOIN public._budget_2026_ini_once u
  ON u.source_initiative = a.target_initiative
ON CONFLICT (source_initiative, budget_department) DO UPDATE
SET action = excluded.action,
    target_initiative_id = excluded.target_initiative_id,
    note = excluded.note;

-- Codo ФОТ ранее удалили вручную (scripts/sql/fix_codo_redistribute_to_fap.sql)
-- и её бюджет был размазан по всем FAP-инициативам с IT.FAP.Management. Чтобы повторный
-- прогон CSV-truth не падал в UNRESOLVED, делаем то же самое автоматически: REDISTRIBUTE
-- по получателям в IT.FAP.Management.
INSERT INTO public.budget_import_2026_rules (source_initiative, budget_department, action, note)
VALUES (
  'Codo ФОТ Q1 25 - Q4 26',
  'IT.FAP.Management',
  'REDISTRIBUTE',
  'Codo ФОТ ранее удалена; делим IT.FAP.Management поровну между остальными FAP-инициативами'
)
ON CONFLICT (source_initiative, budget_department) DO UPDATE
SET action = excluded.action,
    note = excluded.note;

-- 2025-only rows are redistributed inside the same budget department.
-- Чтобы total CSV сохранился (иначе 14,9M «теряются» в воздухе), эти инициативы
-- размазываются поровну между всеми получателями того же budget_department. Побочный
-- эффект — небольшой management-смазывание по живым инициативам того же департамента
-- (для App&Web ~10k/год сверху на каждую). Это лечится позже точечной чисткой ghost'ов
-- (см. scripts/out/ghost_initiatives_2026.tsv), но не ломает тотал бюджета.
INSERT INTO public.budget_import_2026_rules (source_initiative, budget_department, action, note)
SELECT DISTINCT
  s.source_initiative,
  s.budget_department,
  'REDISTRIBUTE',
  '2025-only: распределить внутри budget_department по инициативам 2026'
FROM public._budget_2026_src s
WHERE s.source_initiative IN (
  'Динамическое комбо',
  'Поиск',
  'Умный учет',
  'Computer Vision',
  'Аспелл v2',
  'Аутентификация (УБРАТЬ)',
  'Вставание в очереид по QR кода',
  'Корзина: заказжи самовывоз (скидка 10-20%)',
  'Курьер на город',
  'Мобильное приложение (MVP)',
  'Мощность пиццерии',
  'Поддержка outsource доставки в IMF',
  'Промо ресторана в приложении до 3-го заказа',
  'Улучшение отображение информации на карточках заказов КД и КП',
  'ФОТ Digital Payments Q1-Q2',
  'Peaches ФОТ команды Q1 2025',
  'Чаевые в приложении',
  'Чат "Курьер-Клиент"'
)
ON CONFLICT (source_initiative, budget_department) DO UPDATE
SET action = excluded.action,
    note = excluded.note;

-- Zero rows are ignored unless a stricter rule already exists.
INSERT INTO public.budget_import_2026_rules (source_initiative, budget_department, action, note)
SELECT
  s.source_initiative,
  s.budget_department,
  'SKIP',
  'Auto SKIP: Q1..Q4 sum = 0'
FROM public._budget_2026_src s
WHERE s.q1 + s.q2 + s.q3 + s.q4 = 0
ON CONFLICT (source_initiative, budget_department) DO NOTHING;

-- Final 13 CREATE rules from the previous successful flow.
WITH defs(source_initiative, create_unit, create_team, create_initiative, note) AS (
  VALUES
    ('ФОТ 2025', 'Tech Platform', 'Engineering Tools', 'ФОТ 2025', 'новая команда Engineering Tools'),
    ('ФОТ X-men(u) Q2-Q4 26', 'App&Web', 'X-men(u)', 'ФОТ X-men(u) Q2-Q4 26', 'после fix_xmenu_to_xmenuparenthesis: реальная команда X-men(u)'),
    ('Frontend Guild стоимость', 'Tech Platform', 'Frontend Guild', 'Frontend Guild стоимость', 'новая'),
    ('IT Drinkit.B2B', 'IT Drinkit', 'B2B', 'IT Drinkit.B2B', 'замена Drinkit B2b IT TEAM'),
    ('IT HR', 'IT HR', 'IT HR', 'IT HR', 'новая'),
    ('IT Management', 'IT Management', 'IT Management', 'IT Management', 'новая'),
    ('IT office стоимость команды', 'IT Office', 'IT Office', 'IT office стоимость команды', 'новая'),
    ('IT.Brand', 'IT.Brand', 'IT.Brand', 'IT.Brand', 'новая'),
    ('Mobile', 'App&Web', 'Mobile', 'Mobile', 'новая команда в App&Web'),
    ('Process Core Team стоимост ькоманды', 'Tech Platform', 'Process Core Team', 'Process Core Team стоимост ькоманды', 'новая команда'),
    ('Support стоимость команды', 'FAP', 'Partner Support', 'Partner Support Стоимость команды', 'сложить в Partner Support'),
    ('UX Editors', 'App&Web', 'UX Editors', 'UX Editors', 'новая команда в App&Web'),
    ('Стоимость команды B2B Product Analytics', 'B2B Pizza', 'Product Analytics', 'Стоимость команды B2B Product Analytics', 'новая команда в B2B Pizza')
)
INSERT INTO public.budget_import_2026_rules (
  source_initiative,
  budget_department,
  action,
  target_initiative_id,
  create_unit,
  create_team,
  create_initiative,
  note
)
SELECT
  d.source_initiative,
  s.budget_department,
  'CREATE',
  NULL,
  d.create_unit,
  d.create_team,
  d.create_initiative,
  d.note
FROM defs d
JOIN public._budget_2026_src s USING (source_initiative)
ON CONFLICT (source_initiative, budget_department) DO UPDATE
SET action = excluded.action,
    target_initiative_id = excluded.target_initiative_id,
    create_unit = excluded.create_unit,
    create_team = excluded.create_team,
    create_initiative = excluded.create_initiative,
    note = excluded.note;

CREATE TABLE public._budget_2026_create_defs AS
SELECT DISTINCT
  r.create_unit AS unit,
  r.create_team AS team,
  r.create_initiative AS initiative
FROM public.budget_import_2026_rules r
JOIN public._budget_2026_src s
  ON s.source_initiative = r.source_initiative
 AND s.budget_department = r.budget_department
WHERE r.action = 'CREATE'
  AND r.create_unit IS NOT NULL
  AND r.create_team IS NOT NULL
  AND r.create_initiative IS NOT NULL;

INSERT INTO public.initiatives (
  unit,
  team,
  initiative,
  stakeholders_list,
  description,
  documentation_link,
  stakeholders,
  quarterly_data,
  created_at,
  updated_at
)
SELECT
  d.unit,
  d.team,
  d.initiative,
  array[]::text[],
  '',
  '',
  '',
  '{}'::jsonb,
  timezone('utc'::text, now()),
  timezone('utc'::text, now())
FROM public._budget_2026_create_defs d
LEFT JOIN public.initiatives i
  ON i.unit = d.unit
 AND i.team = d.team
 AND i.initiative = d.initiative
 AND coalesce(i.is_timeline_stub, false) = false
WHERE i.id IS NULL;

UPDATE public.budget_import_2026_rules r
SET target_initiative_id = i.id
FROM public.initiatives i
WHERE r.action = 'CREATE'
  AND i.unit = r.create_unit
  AND i.team = r.create_team
  AND i.initiative = r.create_initiative
  AND coalesce(i.is_timeline_stub, false) = false;

CREATE TABLE public._budget_2026_mapped AS
SELECT
  s.source_initiative,
  s.budget_department,
  coalesce(r.target_initiative_id, u.initiative_id) AS initiative_id,
  s.q1,
  s.q2,
  s.q3,
  s.q4,
  s.is_in_pnl_it
FROM public._budget_2026_src s
LEFT JOIN public.budget_import_2026_rules r
  ON r.source_initiative = s.source_initiative
 AND r.budget_department = s.budget_department
 AND r.action IN ('MAP','CREATE')
LEFT JOIN public._budget_2026_ini_once u
  ON u.source_initiative = s.source_initiative
WHERE coalesce(r.target_initiative_id, u.initiative_id) IS NOT NULL;

CREATE TABLE public._budget_2026_unresolved AS
SELECT s.*
FROM public._budget_2026_src s
LEFT JOIN public._budget_2026_mapped m
  ON m.source_initiative = s.source_initiative
 AND m.budget_department = s.budget_department
LEFT JOIN public.budget_import_2026_rules r
  ON r.source_initiative = s.source_initiative
 AND r.budget_department = s.budget_department
WHERE m.initiative_id IS NULL
  AND coalesce(r.action, '') NOT IN ('REDISTRIBUTE','SKIP')
  AND s.q1 + s.q2 + s.q3 + s.q4 <> 0;

INSERT INTO public.budget_import_2026_exceptions(reason, initiative, details)
SELECT
  'UNRESOLVED',
  source_initiative,
  jsonb_build_object('budget_department', budget_department, 'q1', q1, 'q2', q2, 'q3', q3, 'q4', q4)
FROM public._budget_2026_unresolved;

DO $$
DECLARE
  v_unresolved int;
BEGIN
  SELECT count(*) INTO v_unresolved FROM public._budget_2026_unresolved;
  IF v_unresolved > 0 THEN
    RAISE EXCEPTION 'Есть нерешенные ненулевые пары: %. См. budget_import_2026_exceptions', v_unresolved;
  END IF;
END $$;

CREATE TABLE public._budget_2026_redist_source AS
SELECT
  s.source_initiative,
  s.budget_department,
  s.q1,
  s.q2,
  s.q3,
  s.q4,
  s.is_in_pnl_it
FROM public._budget_2026_src s
JOIN public.budget_import_2026_rules r
  ON r.source_initiative = s.source_initiative
 AND r.budget_department = s.budget_department
WHERE r.action = 'REDISTRIBUTE';

CREATE TABLE public._budget_2026_recipients AS
SELECT budget_department, initiative_id
FROM (
  SELECT budget_department, initiative_id, sum(q1 + q2 + q3 + q4) AS total_sum
  FROM public._budget_2026_mapped
  GROUP BY 1, 2
) t
WHERE total_sum > 0;

INSERT INTO public.budget_import_2026_exceptions(reason, initiative, details)
SELECT
  'REDISTRIBUTE_NO_RECIPIENT',
  rs.source_initiative,
  jsonb_build_object('budget_department', rs.budget_department)
FROM public._budget_2026_redist_source rs
LEFT JOIN public._budget_2026_recipients rc
  ON rc.budget_department = rs.budget_department
WHERE rc.initiative_id IS NULL;

DO $$
DECLARE
  v_no_recipient int;
BEGIN
  SELECT count(*) INTO v_no_recipient
  FROM public.budget_import_2026_exceptions
  WHERE reason = 'REDISTRIBUTE_NO_RECIPIENT';

  IF v_no_recipient > 0 THEN
    RAISE EXCEPTION 'Есть REDISTRIBUTE без получателя: %. См. budget_import_2026_exceptions', v_no_recipient;
  END IF;
END $$;

CREATE TABLE public._budget_2026_redist_alloc AS
WITH recipient_count AS (
  SELECT budget_department, count(*)::numeric AS cnt
  FROM public._budget_2026_recipients
  GROUP BY 1
)
SELECT
  rc.initiative_id,
  rs.budget_department,
  rs.q1 / c.cnt AS q1,
  rs.q2 / c.cnt AS q2,
  rs.q3 / c.cnt AS q3,
  rs.q4 / c.cnt AS q4,
  rs.is_in_pnl_it
FROM public._budget_2026_redist_source rs
JOIN recipient_count c
  ON c.budget_department = rs.budget_department
JOIN public._budget_2026_recipients rc
  ON rc.budget_department = rs.budget_department;

CREATE TABLE public._budget_2026_final_rows AS
SELECT
  initiative_id,
  budget_department,
  sum(q1) AS q1,
  sum(q2) AS q2,
  sum(q3) AS q3,
  sum(q4) AS q4,
  bool_or(is_in_pnl_it) AS is_in_pnl_it
FROM (
  SELECT initiative_id, budget_department, q1, q2, q3, q4, is_in_pnl_it FROM public._budget_2026_mapped
  UNION ALL
  SELECT initiative_id, budget_department, q1, q2, q3, q4, is_in_pnl_it FROM public._budget_2026_redist_alloc
) x
GROUP BY 1, 2;

CREATE TABLE public._budget_2026_final_sum AS
SELECT
  initiative_id,
  sum(q1) AS q1,
  sum(q2) AS q2,
  sum(q3) AS q3,
  sum(q4) AS q4
FROM public._budget_2026_final_rows
GROUP BY 1;

-- Full cleanup: the dashboard split table and quarterly_data must exactly reflect this CSV+rules run.
-- Zero every initiative first, including timeline stubs; otherwise the dashboard can add old
-- quarterly_data from rows that no longer have budget split allocations.
TRUNCATE public.initiative_budget_department_2026;

UPDATE public.initiatives
SET
  quarterly_data =
    jsonb_set(
      jsonb_set(
        jsonb_set(
          jsonb_set(
            jsonb_set(
              jsonb_set(
                jsonb_set(
                  jsonb_set(
                    coalesce(quarterly_data, '{}'::jsonb) - '2025-Q1' - '2025-Q2' - '2025-Q3' - '2025-Q4',
                    '{2026-Q1,cost}', to_jsonb(0::numeric), true
                  ),
                  '{2026-Q1,otherCosts}', '0'::jsonb, true
                ),
                '{2026-Q2,cost}', to_jsonb(0::numeric), true
              ),
              '{2026-Q2,otherCosts}', '0'::jsonb, true
            ),
            '{2026-Q3,cost}', to_jsonb(0::numeric), true
          ),
          '{2026-Q3,otherCosts}', '0'::jsonb, true
        ),
        '{2026-Q4,cost}', to_jsonb(0::numeric), true
      ),
      '{2026-Q4,otherCosts}', '0'::jsonb, true
    ),
  updated_at = timezone('utc'::text, now());

UPDATE public.initiatives i
SET
  quarterly_data =
    jsonb_set(
      jsonb_set(
        jsonb_set(
          jsonb_set(
            jsonb_set(
              jsonb_set(
                jsonb_set(
                  jsonb_set(
                    jsonb_set(
                      jsonb_set(
                        jsonb_set(
                          jsonb_set(
                            coalesce(i.quarterly_data, '{}'::jsonb),
                            '{2026-Q1,cost}', to_jsonb(f.q1), true
                          ),
                          '{2026-Q1,otherCosts}', '0'::jsonb, true
                        ),
                        '{2026-Q1,costFinanceConfirmed}', 'true'::jsonb, true
                      ),
                      '{2026-Q2,cost}', to_jsonb(f.q2), true
                    ),
                    '{2026-Q2,otherCosts}', '0'::jsonb, true
                  ),
                  '{2026-Q2,costFinanceConfirmed}', 'true'::jsonb, true
                ),
                '{2026-Q3,cost}', to_jsonb(f.q3), true
              ),
              '{2026-Q3,otherCosts}', '0'::jsonb, true
            ),
            '{2026-Q3,costFinanceConfirmed}', 'true'::jsonb, true
          ),
          '{2026-Q4,cost}', to_jsonb(f.q4), true
        ),
        '{2026-Q4,otherCosts}', '0'::jsonb, true
      ),
      '{2026-Q4,costFinanceConfirmed}', 'true'::jsonb, true
    ),
  updated_at = timezone('utc'::text, now())
FROM public._budget_2026_final_sum f
WHERE i.id = f.initiative_id;

INSERT INTO public.initiative_budget_department_2026 (
  initiative_id,
  budget_department,
  q1,
  q2,
  q3,
  q4,
  is_in_pnl_it,
  created_at,
  updated_at
)
SELECT
  initiative_id,
  budget_department,
  q1,
  q2,
  q3,
  q4,
  is_in_pnl_it,
  timezone('utc'::text, now()),
  timezone('utc'::text, now())
FROM public._budget_2026_final_rows
ON CONFLICT (initiative_id, budget_department) DO UPDATE SET
  q1 = excluded.q1,
  q2 = excluded.q2,
  q3 = excluded.q3,
  q4 = excluded.q4,
  is_in_pnl_it = excluded.is_in_pnl_it,
  updated_at = excluded.updated_at;

COMMIT;

SELECT
  (SELECT count(*) FROM public._budget_truth_csv) AS truth_rows,
  (SELECT count(*) FROM public.initiative_budget_department_2026) AS split_rows,
  (SELECT count(*) FROM public.budget_import_2026_exceptions) AS exception_rows,
  (SELECT round(sum(q1 + q2 + q3 + q4))::bigint FROM public._budget_truth_csv) AS truth_total,
  (SELECT round(sum(q1 + q2 + q3 + q4))::bigint FROM public.initiative_budget_department_2026) AS split_total,
  (SELECT round(sum(q1 + q2 + q3 + q4))::bigint FROM public._budget_truth_csv WHERE is_in_pnl_it) AS truth_pnl_it_total,
  (SELECT round(sum(q1 + q2 + q3 + q4))::bigint FROM public.initiative_budget_department_2026 WHERE is_in_pnl_it) AS split_pnl_it_total;

SELECT reason, initiative, details
FROM public.budget_import_2026_exceptions
ORDER BY reason, initiative
LIMIT 200;
