// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (import.meta.env.DEV && (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY)) {
  console.warn(
    '[Supabase] VITE_SUPABASE_URL или VITE_SUPABASE_PUBLISHABLE_KEY не заданы в .env. Авторизация и данные не будут работать.'
  );
}

// Однократная проверка доступности бэкенда в dev (диагностика pending)
if (import.meta.env.DEV && SUPABASE_URL) {
  const url = `${SUPABASE_URL.replace(/\/$/, '')}/rest/v1/`;
  const controller = new AbortController();
  const timeoutMs = 3000;
  const timeoutId = setTimeout(() => controller.abort(), timeoutMs);
  fetch(url, { method: 'HEAD', signal: controller.signal })
    .then(() => {
      clearTimeout(timeoutId);
      console.info('[Supabase] Подключение к бэкенду доступно:', url);
    })
    .catch((err) => {
      clearTimeout(timeoutId);
      if (err.name === 'AbortError') {
        console.warn('[Supabase] Проверка подключения к бэкенду: таймаут', timeoutMs / 1000, 'с. Возможна пауза проекта (Free tier) или сеть:', url);
      } else {
        console.warn('[Supabase] Проверка подключения к бэкенду не удалась:', err.message || err, url);
      }
    });
}

export const supabase = createClient<Database>(
  SUPABASE_URL || '',
  SUPABASE_PUBLISHABLE_KEY || '',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);