// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (import.meta.env.DEV && (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY)) {
  console.warn(
    '[Supabase] VITE_SUPABASE_URL или VITE_SUPABASE_PUBLISHABLE_KEY не заданы в .env. Авторизация и данные не будут работать.'
  );
}

// Однократная проверка в dev: PostgREST с publishable/anon ключом (а не /auth/v1/health — там часто 401 без service role)
if (import.meta.env.DEV && SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
  const base = SUPABASE_URL.replace(/\/$/, '');
  const url = `${base}/rest/v1/`;
  const controller = new AbortController();
  const timeoutMs = 3000;
  const timeoutId = setTimeout(() => controller.abort(), timeoutMs);
  fetch(url, {
    method: 'GET',
    signal: controller.signal,
    headers: {
      apikey: SUPABASE_PUBLISHABLE_KEY,
      Authorization: `Bearer ${SUPABASE_PUBLISHABLE_KEY}`,
    },
  })
    .then((res) => {
      clearTimeout(timeoutId);
      if (res.ok) {
        console.info('[Supabase] Подключение к бэкенду доступно:', base);
      } else {
        console.warn('[Supabase] rest/v1 ответил', res.status, '(проверьте ключи в .env):', url);
      }
    })
    .catch((err) => {
      clearTimeout(timeoutId);
      if (err.name === 'AbortError') {
        console.warn('[Supabase] Проверка подключения к бэкенду: таймаут', timeoutMs / 1000, 'с. Возможна пауза проекта (Free tier) или сеть:', url);
      } else {
        console.warn('[Supabase] Проверка подключения к бэкенду не удалась:', err.message || err, url);
      }
    });
}

export const supabase = createClient<Database>(
  SUPABASE_URL || '',
  SUPABASE_PUBLISHABLE_KEY || '',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);